name: medkit
description: An app for common people to help them know about different diseases/symptoms and there medications.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.11.0
  firebase_analytics: ^9.0.5
  simple_animations: ^4.0.1
  page_transition: ^2.0.4
  cupertino_icons: ^0.1.2
  google_fonts: ^2.2.0
  toast: ^0.1.5
  cloud_firestore: ^3.1.6
  google_sign_in: ^5.2.3
  firebase_auth: ^3.3.5
  url_launcher: ^6.0.18
  location: ^4.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
   - assets/
